/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Calculator: typeof import('./src/components/Calculator.vue')['default']
    CalculatorInput: typeof import('./src/components/CalculatorInput.vue')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    DarkModeToggle: typeof import('./src/components/DarkModeToggle.vue')['default']
    ExRateChart: typeof import('./src/components/ExRateChart.vue')['default']
    ExRateChartConfig: typeof import('./src/components/ExRateChartConfig.vue')['default']
    Fluid: typeof import('primevue/fluid')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
